### ISSUE TITLE
restart_process extension and Args

### ISSUE THREAD

**Issue by zkutasi** [tilt-dev/tilt-extensions#169]
Hi,

We have the following use-case:
1. We have a helm chart with a deployment, and in this helm chart, we have defined lots of arguments for Java for example
2. We have a Dockerfile, in this dockerfile, we specify the ENTRYPOINT as 
ENTRYPOINT ["/bin/bash", "-e", "./entrypoint.sh"]

3. This entrypoint.sh script is launching our Java app, with arguments all around (JVM plus App parameters)... and we use the fact that by default, Docker execution passes all extra arguments into the entrypoint without specifying it anywhere
4. Now, with Tilt, this does not seem to work, as kind-of stated in the README here: https://github.com/tilt-dev/tilt-extensions/tree/master/restart_process, however you state here that there is a possibility to use Args... but not documented
5. What happens is that in the end, in docker I see this for example with "kubectl describe"
```
 containers:
  - args:
    - -Xms1g -Xmx3g
    - -Dspring.config.location=classpath:application.yaml,file:///etc/spring/custom-application.yaml
    - -Dlog4j.configurationFactory=xxx
    - -Dcore.tls.enabled=false
    - -Dcore.application.name=app
    - -Dcore.logtransformer.port=5014
    - com.company.Application
   command:
    - /tilt-restart-wrapper
    - --watch_file=/tmp/.restart-proc
    - sh
    - -c
    - /bin/bash -e ./entrypoint.sh
   env:

```
and with "docker inspect":

```
        "Path": "/tilt-restart-wrapper",
        "Args": [
            "--watch_file=/tmp/.restart-proc",
            "sh",
            "-c",
            "/bin/bash -e ./entrypoint.sh",
            "-Xms1g -Xmx3g",
            "-Dspring.config.location=classpath:application.yaml,file:///etc/spring/custom-application.yaml",
            "-Dlog4j.configurationFactory=xxx",
            "-Dcore.tls.enabled=false",
            "-Dcore.application.name=app",
            "-Dcore.logtransformer.port=5014",
            "com.company.Application"
        ],

```
As you can see, TIlt replaced the command, and it gets "distributed" into path and args... and the extra arguments coming from helm are "appended" at the end... however, in entrypoint.sh, absolutley no arguments are passed in. I do not really know how these values get merged together into a single command line, how they are escaped, quoted etc...

Could you perhaps help us to find a nice way around this issue? Maybe document some of them in the Readme? Preferrably one that does not need to touch the production code that we intend to have. What we were thinking so far:
1. Use some WA from here: https://docs.tilt.dev/live_update_reference.html#workarounds-for-restarting-your-process
2. Instead of Args, use an Env variable ... This is not good for us for several reasons
3. Add a small trick to the TIltfile, to parse the deployment YAML, and extract the args, and set the new entrypoint passing these args explicitly
