### ISSUE TITLE
[bug] namespace_inject assumes metadata key will always exist

### ISSUE THREAD

**Issue by phroggyy** [tilt-dev/tilt-extensions#51]
_First reported in #tilt in Kubernetes Slack_

the `namespace_inject` function attempts to set a namespace for every `template` on a kubernetes resource. However, it makes the false assumption that the inner `template` will always have a `metadata` key. This is the case for all top-level resources, and also for resources such as `Deployment` but **not** for `CronJob`.

The following code is what's causing problems:

```
    for k, v in o.items():
      if k == 'template':
        v['metadata']['namespace'] = ns
      if type(v) == 'dict' or type(v) == 'list':
        _set_template_namespace(v, ns)
```

the function will keep descending recursively into every template. In my case, the offending yaml is this:

```
# Source: jobs/charts/laravel/templates/scheduler.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: leo-jobs-scheduler
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - configMap:
                name: oauth-public-key
              name: oauth-public
          containers:
            - name: laravel-scheduler
              image: eu.gcr.io/project/image:latest
              command: ["php", "artisan", "schedule:run"]
              volumeMounts:
                - mountPath: /app/storage/oauth-public.key
                  name: oauth-public
                  readOnly: true
                  subPath: oauth-public.key
              envFrom:
                - secretRef:
                    name: leo-jobs-env
```

Note `spec.jobTemplate.spec.template`: it is a template key (and thus gets picked up), but doesn't contain a metadata section
