### ISSUE TITLE
Values file not taken into account in helm_remote

### ISSUE THREAD

**Issue by MacherelR** [tilt-dev/tilt-extensions#585]
Hello, 
I'm trying to deploy redpanda inside a tilt development environment, and to do so I have this setup in my tiltfile :
```
load('ext://helm_remote', 'helm_remote')
load('ext://cert_manager', 'deploy_cert_manager')
deploy_cert_manager()
helm_remote('redpanda',
            repo_name='redpanda',
            repo_url='https://charts.redpanda.com',
            version='5.7.31',
            values=['./k8s/redpanda/values.yaml'])
```
Now my values.yaml file looks like this :
```
redpanda:
  enabled: true
  nameOverride: redpanda
  fullnameOverride: redpanda
  statefulset:
    replicas: 1
  storage:
    persistentVolume:
      size: 1Gi
  resources:
    cpu:
      cores: 2  # recommended in production: 4+
    memory:
      # enable_memory_locking: false  # recommended in production
      container:
        max: 5Gi  # recommended in production: 10Gi+
  listeners:
    kafka:
      port: 9092
      tls:
        enabled: false
      external:
        default:
          enabled: false
    admin:
      port: 9644
      tls:
        enabled: false
    rpc:
      port: 33145
      tls:
        enabled: false
    schema_registry:
      port: 8081
      tls:
        enabled: false
  external:
    enabled: false
  tls:
    enabled: false
  console:
    nameOverride: redpanda-console
    fullnameOverride: redpanda-console
  monitoring:
    enabled: true
  config:
    cluster:
      auto_create_topics_enabled: true
  secrets:
    tls:
      kafka: ""
      admin: ""
      rpc: ""
      schema_registry: ""
```
And first thing I realized is that the values.yaml file doesn't seem to be taken into account as it deploys with redpanda's default replicas value of 3. I tried setting "statefulset.replicas = 1" within the ```set=['statefulset.replicas=1']``` and this works but as I have multiple values that need to be modified I wouldn't want to write every value inside the set option... 
Am I using the wrong extension or does anyone has any idea what's wrong ?
